GenericElement: {
  shape: class
  +new(): "(path,id)"
}

PrintablePlug:{
    shape: class
    +new(): ""   
    +setName(): ""
    +setColor(): ""
    -name
    -colors
    -shapes
}

InternalPlug{
    shape: class
    +new(): ""
    -completed
}

GenericElement-->PrintablePlug
GenericElement-->InternalPlug

Connector: {
    shape: class
    +new(): ""
  }

Slider: {
    shape: class
    +new(): ""
  }

GenericBus: {
    shape: class
    +new(): ""
  }

PrintablePlug-->Slider
PrintablePlug-->GenericBus
PrintablePlug-->Connector

MainL: {
    shape: class
    +new(): ""
  }

MainR: {
    shape: class
    +new(): ""
  }

Mono: {
    shape: class
    +new(): ""
}

SoloL: {
    shape: class
    +new(): ""
}
SoloR: {
  shape: class
  +new(): ""
}


MixBus: {
    shape: class
    +new(): ""
}

GenericBus-->MainL
GenericBus-->MainR
GenericBus-->Mono
GenericBus-->SoloL
GenericBus-->SoloR
GenericBus-->Mixbus








  