# fixed hardware (display always)

direction:down

console: {
  SOLO.style.fill: "#ffff3f"
  M.style.fill: "#8ecae6"
  STEREO:{
    L
    R
    style.fill: "#8ecae6"
    }
  shape: parallelogram
  style.fill: "#ffe5d9"
}

local:{
  block1-8.shape:cloud
  block9-16.shape:cloud
  block17-24.shape:cloud
  block25-32.shape:cloud
  style.fill: "#00afb9"
}

output: {
  block1-4{
    xlr1: {
      shape: circle
      style.fill: "#bf0603"
    }
    xlr2: {
      shape: circle
      style.fill: "#bf0603"
    }
    xlr3: {
      shape: circle
      style.fill: "#bf0603"
    }
    xlr4: {
      shape: circle
      style.fill: "#bf0603"
    }
    shape:cloud
  }
  block5-8{
    xlr5: {
      shape: circle
      style.fill: "#bf0603"
    }
    xlr6: {
      shape: circle
      style.fill: "#bf0603"
    }
    xlr7: {
      shape: circle
      style.fill: "#bf0603"
    }
    xlr8: {
      shape: circle
      style.fill: "#bf0603"
    }
    shape:cloud
  }
 
  shape: rectangle
  style.fill: "#00afb9"

}


consoleOutput:{
	block1-4.shape:cloud
	block5-8.shape:cloud
	block9-12.shape:cloud
	block13-16.shape:cloud
	shape:step
	style.fill:"#c9184a"
}



xusb:{
  block1-8.shape:cloud
  block9-16.shape:cloud
  block17-24.shape:cloud
  block25-32.shape:cloud
  style.fill: "#f07167"
}

aux: {
  jack_in1: {
    shape: circle
    style.fill: "#8ac926"
  }
  jack_in2: {
    shape: circle
    style.fill: "#8ac926"
  }
  jack_in3: {
    shape: circle
    style.fill: "#8ac926"
  }
  jack_in4: {
    shape: circle
    style.fill: "#8ac926"
  }
  jack_in5: {
    shape: circle
    style.fill: "#8ac926"
  }
  jack_in6: {
    shape: circle
    style.fill: "#8ac926"
  }
  jack_out1: {
    shape: circle
    style.fill: "#bf0603"
    
  }
  jack_out2: {
    shape: circle
    style.fill: "#bf0603"
  }
  jack_out3: {
    shape: circle
    style.fill: "#bf0603"
  }
  jack_out4: {
    shape: circle
    style.fill: "#bf0603"
  }
  jack_out5: {
    shape: circle
    style.fill: "#bf0603"
  }
  jack_out6: {
    shape: circle
    style.fill: "#bf0603"
  } 
  shape: rectangle
  style.fill: "#00afb9"
}


usbkey: {
  recL: {
    shape: circle
    style.fill: "#8ac926"
  }
  recR: {
    shape: circle
    style.fill: "#8ac926"
  }
  playL: {
    shape: circle
    style.fill: "#bf0603"
  }
  playR: {
    shape: circle
    style.fill: "#bf0603"
  }
  shape: rectangle
  style.fill: "#f07167"
}




# some minimal connectors

console: {
  slider1.label:ch1
  bus1:{
    label:MixBus1
    style.fill: "#ffb703"
  }
}

local.block1-8: {
  xlr1: {
    shape: circle
    style.fill: "#8ac926"
  }
  xlr2: {
    shape: circle
    style.fill: "#8ac926"
  }
}

xusb.block1-8: {
    return1: {
      shape: circle
      style.fill: "#8ac926"
    }
   
    send1: {
      shape: circle
      style.fill: "#bf0603"
    }   
}

consoleOutput.block1-4:{
	out1: {
		shape: circle
		style.fill: "#a0a0a0"
	  }
}

#end
# feeding USB send 1
#trying to print style for object local.block1-4.xlr1

#style is here below
local.block1-4.xlr1: {
	shape: circle
    style.fill: '#8ac926'
}
#trying to print style for object xusb.block1-8.send1

#style is here below
xusb.block1-8.send1: {
	shape: circle
    style.fill: '#bf0603'
}
local.block1-4.xlr1 -> xusb.block1-8.send1
# feeding USB send 2
#trying to print style for object local.block1-4.xlr2

#style is here below
local.block1-4.xlr2: {
	shape: circle
    style.fill: '#8ac926'
}
#trying to print style for object xusb.block1-8.send2

#style is here below
xusb.block1-8.send2: {
	shape: circle
    style.fill: '#bf0603'
}
local.block1-4.xlr2 -> xusb.block1-8.send2
# feeding USB send 3
#trying to print style for object local.block1-4.xlr3

#style is here below
local.block1-4.xlr3: {
	shape: circle
    style.fill: '#8ac926'
}
#trying to print style for object xusb.block1-8.send3

#style is here below
xusb.block1-8.send3: {
	shape: circle
    style.fill: '#bf0603'
}
local.block1-4.xlr3 -> xusb.block1-8.send3
# feeding USB send 4
#trying to print style for object local.block1-4.xlr4

#style is here below
local.block1-4.xlr4: {
	shape: circle
    style.fill: '#8ac926'
}
#trying to print style for object xusb.block1-8.send4

#style is here below
xusb.block1-8.send4: {
	shape: circle
    style.fill: '#bf0603'
}
local.block1-4.xlr4 -> xusb.block1-8.send4
# feeding USB send 5
#trying to print style for object local.block5-8.xlr5

#style is here below
local.block5-8.xlr5: {
	shape: circle
    style.fill: '#8ac926'
}
#trying to print style for object xusb.block1-8.send5

#style is here below
xusb.block1-8.send5: {
	shape: circle
    style.fill: '#bf0603'
}
local.block5-8.xlr5 -> xusb.block1-8.send5
# feeding USB send 6
#trying to print style for object local.block5-8.xlr6

#style is here below
local.block5-8.xlr6: {
	shape: circle
    style.fill: '#8ac926'
}
#trying to print style for object xusb.block1-8.send6

#style is here below
xusb.block1-8.send6: {
	shape: circle
    style.fill: '#bf0603'
}
local.block5-8.xlr6 -> xusb.block1-8.send6
# feeding USB send 7
#trying to print style for object local.block5-8.xlr7

#style is here below
local.block5-8.xlr7: {
	shape: circle
    style.fill: '#8ac926'
}
#trying to print style for object xusb.block1-8.send7

#style is here below
xusb.block1-8.send7: {
	shape: circle
    style.fill: '#bf0603'
}
local.block5-8.xlr7 -> xusb.block1-8.send7
# feeding USB send 8
#trying to print style for object local.block5-8.xlr8

#style is here below
local.block5-8.xlr8: {
	shape: circle
    style.fill: '#8ac926'
}
#trying to print style for object xusb.block1-8.send8

#style is here below
xusb.block1-8.send8: {
	shape: circle
    style.fill: '#bf0603'
}
local.block5-8.xlr8 -> xusb.block1-8.send8
# feeding USB send 9
#trying to print style for object local.block9-12.xlr9

#style is here below
local.block9-12.xlr9: {
	shape: circle
    style.fill: '#8ac926'
}
#trying to print style for object xusb.block9-16.send9

#style is here below
xusb.block9-16.send9: {
	shape: circle
    style.fill: '#bf0603'
}
local.block9-12.xlr9 -> xusb.block9-16.send9
# feeding USB send 10
#trying to print style for object local.block9-12.xlr10

#style is here below
local.block9-12.xlr10: {
	shape: circle
    style.fill: '#8ac926'
}
#trying to print style for object xusb.block9-16.send10

#style is here below
xusb.block9-16.send10: {
	shape: circle
    style.fill: '#bf0603'
}
local.block9-12.xlr10 -> xusb.block9-16.send10
# feeding USB send 11
#trying to print style for object local.block9-12.xlr11

#style is here below
local.block9-12.xlr11: {
	shape: circle
    style.fill: '#8ac926'
}
#trying to print style for object xusb.block9-16.send11

#style is here below
xusb.block9-16.send11: {
	shape: circle
    style.fill: '#bf0603'
}
local.block9-12.xlr11 -> xusb.block9-16.send11
# feeding USB send 12
#trying to print style for object local.block9-12.xlr12

#style is here below
local.block9-12.xlr12: {
	shape: circle
    style.fill: '#8ac926'
}
#trying to print style for object xusb.block9-16.send12

#style is here below
xusb.block9-16.send12: {
	shape: circle
    style.fill: '#bf0603'
}
local.block9-12.xlr12 -> xusb.block9-16.send12
# feeding USB send 13
#trying to print style for object local.block13-16.xlr13

#style is here below
local.block13-16.xlr13: {
	shape: circle
    style.fill: '#8ac926'
}
#trying to print style for object xusb.block9-16.send13

#style is here below
xusb.block9-16.send13: {
	shape: circle
    style.fill: '#bf0603'
}
local.block13-16.xlr13 -> xusb.block9-16.send13
# feeding USB send 14
#trying to print style for object local.block13-16.xlr14

#style is here below
local.block13-16.xlr14: {
	shape: circle
    style.fill: '#8ac926'
}
#trying to print style for object xusb.block9-16.send14

#style is here below
xusb.block9-16.send14: {
	shape: circle
    style.fill: '#bf0603'
}
local.block13-16.xlr14 -> xusb.block9-16.send14
# feeding USB send 15
#trying to print style for object local.block13-16.xlr15

#style is here below
local.block13-16.xlr15: {
	shape: circle
    style.fill: '#8ac926'
}
#trying to print style for object xusb.block9-16.send15

#style is here below
xusb.block9-16.send15: {
	shape: circle
    style.fill: '#bf0603'
}
local.block13-16.xlr15 -> xusb.block9-16.send15
# feeding USB send 16
#trying to print style for object local.block13-16.xlr16

#style is here below
local.block13-16.xlr16: {
	shape: circle
    style.fill: '#8ac926'
}
#trying to print style for object xusb.block9-16.send16

#style is here below
xusb.block9-16.send16: {
	shape: circle
    style.fill: '#bf0603'
}
local.block13-16.xlr16 -> xusb.block9-16.send16
# feeding USB send 17
#trying to print style for object consoleOutput.block1-4.xlr1
#but no style has been defined for consoleOutput.block.xlr
#trying to print style for object xusb.block17-24.send17

#style is here below
xusb.block17-24.send17: {
	shape: circle
    style.fill: '#bf0603'
}
consoleOutput.block1-4.xlr1 -> xusb.block17-24.send17
# feeding USB send 18
#trying to print style for object consoleOutput.block1-4.xlr2
#but no style has been defined for consoleOutput.block.xlr
#trying to print style for object xusb.block17-24.send18

#style is here below
xusb.block17-24.send18: {
	shape: circle
    style.fill: '#bf0603'
}
consoleOutput.block1-4.xlr2 -> xusb.block17-24.send18
# feeding USB send 19
#trying to print style for object consoleOutput.block1-4.xlr3
#but no style has been defined for consoleOutput.block.xlr
#trying to print style for object xusb.block17-24.send19

#style is here below
xusb.block17-24.send19: {
	shape: circle
    style.fill: '#bf0603'
}
consoleOutput.block1-4.xlr3 -> xusb.block17-24.send19
# feeding USB send 20
#trying to print style for object consoleOutput.block1-4.xlr4
#but no style has been defined for consoleOutput.block.xlr
#trying to print style for object xusb.block17-24.send20

#style is here below
xusb.block17-24.send20: {
	shape: circle
    style.fill: '#bf0603'
}
consoleOutput.block1-4.xlr4 -> xusb.block17-24.send20
# feeding USB send 21
#trying to print style for object consoleOutput.block5-8.xlr5
#but no style has been defined for consoleOutput.block.xlr
#trying to print style for object xusb.block17-24.send21

#style is here below
xusb.block17-24.send21: {
	shape: circle
    style.fill: '#bf0603'
}
consoleOutput.block5-8.xlr5 -> xusb.block17-24.send21
# feeding USB send 22
#trying to print style for object consoleOutput.block5-8.xlr6
#but no style has been defined for consoleOutput.block.xlr
#trying to print style for object xusb.block17-24.send22

#style is here below
xusb.block17-24.send22: {
	shape: circle
    style.fill: '#bf0603'
}
consoleOutput.block5-8.xlr6 -> xusb.block17-24.send22
# feeding USB send 23
#trying to print style for object consoleOutput.block5-8.xlr7
#but no style has been defined for consoleOutput.block.xlr
#trying to print style for object xusb.block17-24.send23

#style is here below
xusb.block17-24.send23: {
	shape: circle
    style.fill: '#bf0603'
}
consoleOutput.block5-8.xlr7 -> xusb.block17-24.send23
# feeding USB send 24
#trying to print style for object consoleOutput.block5-8.xlr8
#but no style has been defined for consoleOutput.block.xlr
#trying to print style for object xusb.block17-24.send24

#style is here below
xusb.block17-24.send24: {
	shape: circle
    style.fill: '#bf0603'
}
consoleOutput.block5-8.xlr8 -> xusb.block17-24.send24
# feeding USB send 25
#trying to print style for object consoleOutput.block9-12.xlr9
#but no style has been defined for consoleOutput.block.xlr
#trying to print style for object xusb.block25-32.send25

#style is here below
xusb.block25-32.send25: {
	shape: circle
    style.fill: '#bf0603'
}
consoleOutput.block9-12.xlr9 -> xusb.block25-32.send25
# feeding USB send 26
#trying to print style for object consoleOutput.block9-12.xlr10
#but no style has been defined for consoleOutput.block.xlr
#trying to print style for object xusb.block25-32.send26

#style is here below
xusb.block25-32.send26: {
	shape: circle
    style.fill: '#bf0603'
}
consoleOutput.block9-12.xlr10 -> xusb.block25-32.send26
# feeding USB send 27
#trying to print style for object consoleOutput.block9-12.xlr11
#but no style has been defined for consoleOutput.block.xlr
#trying to print style for object xusb.block25-32.send27

#style is here below
xusb.block25-32.send27: {
	shape: circle
    style.fill: '#bf0603'
}
consoleOutput.block9-12.xlr11 -> xusb.block25-32.send27
# feeding USB send 28
#trying to print style for object consoleOutput.block9-12.xlr12
#but no style has been defined for consoleOutput.block.xlr
#trying to print style for object xusb.block25-32.send28

#style is here below
xusb.block25-32.send28: {
	shape: circle
    style.fill: '#bf0603'
}
consoleOutput.block9-12.xlr12 -> xusb.block25-32.send28
# feeding USB send 29
#trying to print style for object consoleOutput.block13-16.xlr13
#but no style has been defined for consoleOutput.block.xlr
#trying to print style for object xusb.block25-32.send29

#style is here below
xusb.block25-32.send29: {
	shape: circle
    style.fill: '#bf0603'
}
consoleOutput.block13-16.xlr13 -> xusb.block25-32.send29
# feeding USB send 30
#trying to print style for object consoleOutput.block13-16.xlr14
#but no style has been defined for consoleOutput.block.xlr
#trying to print style for object xusb.block25-32.send30

#style is here below
xusb.block25-32.send30: {
	shape: circle
    style.fill: '#bf0603'
}
consoleOutput.block13-16.xlr14 -> xusb.block25-32.send30
# feeding USB send 31
#trying to print style for object consoleOutput.block13-16.xlr15
#but no style has been defined for consoleOutput.block.xlr
#trying to print style for object xusb.block25-32.send31

#style is here below
xusb.block25-32.send31: {
	shape: circle
    style.fill: '#bf0603'
}
consoleOutput.block13-16.xlr15 -> xusb.block25-32.send31
# feeding USB send 32
#trying to print style for object consoleOutput.block13-16.xlr16
#but no style has been defined for consoleOutput.block.xlr
#trying to print style for object xusb.block25-32.send32

#style is here below
xusb.block25-32.send32: {
	shape: circle
    style.fill: '#bf0603'
}
consoleOutput.block13-16.xlr16 -> xusb.block25-32.send32
#trying to print style for object consoleOutput.block1-4.out1

#style is here below
consoleOutput.block1-4.out1: {
	shape: circle
    style.fill: '#a0a0a0'
}
#trying to print style for object output.block1-4.xlr1

#style is here below
output.block1-4.xlr1: {
	shape: circle
    style.fill: '#bf0603'
}
consoleOutput.block1-4.out1 -> output.block1-4.xlr1
#trying to print style for object consoleOutput.block1-4.out2

#style is here below
consoleOutput.block1-4.out2: {
	shape: circle
    style.fill: '#a0a0a0'
}
#trying to print style for object output.block1-4.xlr2

#style is here below
output.block1-4.xlr2: {
	shape: circle
    style.fill: '#bf0603'
}
consoleOutput.block1-4.out2 -> output.block1-4.xlr2
#trying to print style for object consoleOutput.block1-4.out3

#style is here below
consoleOutput.block1-4.out3: {
	shape: circle
    style.fill: '#a0a0a0'
}
#trying to print style for object output.block1-4.xlr3

#style is here below
output.block1-4.xlr3: {
	shape: circle
    style.fill: '#bf0603'
}
consoleOutput.block1-4.out3 -> output.block1-4.xlr3
#trying to print style for object consoleOutput.block1-4.out4

#style is here below
consoleOutput.block1-4.out4: {
	shape: circle
    style.fill: '#a0a0a0'
}
#trying to print style for object output.block1-4.xlr4

#style is here below
output.block1-4.xlr4: {
	shape: circle
    style.fill: '#bf0603'
}
consoleOutput.block1-4.out4 -> output.block1-4.xlr4
#trying to print style for object consoleOutput.block5-8.out5

#style is here below
consoleOutput.block5-8.out5: {
	shape: circle
    style.fill: '#a0a0a0'
}
#trying to print style for object output.block5-8.xlr5

#style is here below
output.block5-8.xlr5: {
	shape: circle
    style.fill: '#bf0603'
}
consoleOutput.block5-8.out5 -> output.block5-8.xlr5
#trying to print style for object consoleOutput.block5-8.out6

#style is here below
consoleOutput.block5-8.out6: {
	shape: circle
    style.fill: '#a0a0a0'
}
#trying to print style for object output.block5-8.xlr6

#style is here below
output.block5-8.xlr6: {
	shape: circle
    style.fill: '#bf0603'
}
consoleOutput.block5-8.out6 -> output.block5-8.xlr6
#trying to print style for object consoleOutput.block5-8.out7

#style is here below
consoleOutput.block5-8.out7: {
	shape: circle
    style.fill: '#a0a0a0'
}
#trying to print style for object output.block5-8.xlr7

#style is here below
output.block5-8.xlr7: {
	shape: circle
    style.fill: '#bf0603'
}
consoleOutput.block5-8.out7 -> output.block5-8.xlr7
#trying to print style for object consoleOutput.block5-8.out8

#style is here below
consoleOutput.block5-8.out8: {
	shape: circle
    style.fill: '#a0a0a0'
}
#trying to print style for object output.block5-8.xlr8

#style is here below
output.block5-8.xlr8: {
	shape: circle
    style.fill: '#bf0603'
}
consoleOutput.block5-8.out8 -> output.block5-8.xlr8
console.slider7.label: BasiL
#trying to print style for object xusb.block25-32.return31

#style is here below
xusb.block25-32.return31: {
	shape: circle
    style.fill: '#8ac926'
}
xusb.block25-32.return31->console.slider7
console.slider7 -> console.STEREO
console.slider7 -> console.bus1
console.slider8.label: BasiR
#trying to print style for object xusb.block25-32.return32

#style is here below
xusb.block25-32.return32: {
	shape: circle
    style.fill: '#8ac926'
}
xusb.block25-32.return32->console.slider8
console.slider8 -> console.STEREO
console.slider8 -> console.bus1
console.bus1 -> consoleOutput.block1-4.out1
#trying to print style for object consoleOutput.block1-4.out1
#but it was already printed
#trying to print style for object consoleOutput.block1-4.out2
#but it was already printed
#trying to print style for object consoleOutput.block1-4.out3
#but it was already printed
#trying to print style for object consoleOutput.block1-4.out4
#but it was already printed
#trying to print style for object consoleOutput.block5-8.out5
#but it was already printed
#trying to print style for object consoleOutput.block5-8.out6
#but it was already printed
console.STEREO.L -> consoleOutput.block5-8.out7
#trying to print style for object consoleOutput.block5-8.out7
#but it was already printed
console.STEREO.R -> consoleOutput.block5-8.out8
#trying to print style for object consoleOutput.block5-8.out8
#but it was already printed
#trying to print style for object consoleOutput.block9-12.out9

#style is here below
consoleOutput.block9-12.out9: {
	shape: circle
    style.fill: '#a0a0a0'
}
#trying to print style for object consoleOutput.block9-12.out10

#style is here below
consoleOutput.block9-12.out10: {
	shape: circle
    style.fill: '#a0a0a0'
}
#trying to print style for object consoleOutput.block9-12.out11

#style is here below
consoleOutput.block9-12.out11: {
	shape: circle
    style.fill: '#a0a0a0'
}
#trying to print style for object consoleOutput.block9-12.out12

#style is here below
consoleOutput.block9-12.out12: {
	shape: circle
    style.fill: '#a0a0a0'
}
#trying to print style for object consoleOutput.block13-16.out13

#style is here below
consoleOutput.block13-16.out13: {
	shape: circle
    style.fill: '#a0a0a0'
}
#trying to print style for object consoleOutput.block13-16.out14

#style is here below
consoleOutput.block13-16.out14: {
	shape: circle
    style.fill: '#a0a0a0'
}
#trying to print style for object consoleOutput.block13-16.out15

#style is here below
consoleOutput.block13-16.out15: {
	shape: circle
    style.fill: '#a0a0a0'
}
#trying to print style for object consoleOutput.block13-16.out16

#style is here below
consoleOutput.block13-16.out16: {
	shape: circle
    style.fill: '#a0a0a0'
}
