# fixed hardware (display always)

direction: down

console: {
  SOLO.style.fill: "#ffff3f"
  M.style.fill: "#8ecae6"
  STEREO: {
    L
    R
    style.fill: "#8ecae6"
  }
  shape: parallelogram
  style.fill: "#ffe5d9"
}

phisicalInput: {
  block1-8.shape: cloud
  block9-16.shape: cloud
  block17-24.shape: cloud
  block25-32.shape: cloud
  style.fill: "#00afb9"
}

phisicalOutput: {
  block1-4: {
    xlr1: {
      shape: circle
      style.fill: "#bf0603"
    }
    xlr2: {
      shape: circle
      style.fill: "#bf0603"
    }
    xlr3: {
      shape: circle
      style.fill: "#bf0603"
    }
    xlr4: {
      shape: circle
      style.fill: "#bf0603"
    }

    shape: cloud
  }

  block5-8: {
    xlr5: {
      shape: circle
      style.fill: "#bf0603"
    }
    xlr6: {
      shape: circle
      style.fill: "#bf0603"
    }
    xlr7: {
      shape: circle
      style.fill: "#bf0603"
    }
    xlr8: {
      shape: circle
      style.fill: "#bf0603"
    }
    shape: cloud
  }

  shape: rectangle
  style.fill: "#00afb9"
}

internalInput: {
  block1-8.shape: cloud
  block9-16.shape: cloud
  block17-24.shape: cloud
  block25-32.shape: cloud
  shape: step
  style.fill: "#4f772d"
}

internalOutput: {
  block1-8.shape: cloud
  block9-16.shape: cloud
  shape: step
  style.fill: "#c9184a"
}

xusb: {
  block1-8.shape: cloud
  block9-16.shape: cloud
  block17-24.shape: cloud
  block25-32.shape: cloud
  style.fill: "#f07167"
}

aux: {
  jackIn1: {
    shape: circle
    style.fill: "#8ac926"
  }
  jackIn2: {
    shape: circle
    style.fill: "#8ac926"
  }
  jackIn3: {
    shape: circle
    style.fill: "#8ac926"
  }
  jackIn4: {
    shape: circle
    style.fill: "#8ac926"
  }
  jackIn5: {
    shape: circle
    style.fill: "#8ac926"
  }
  jackIn6: {
    shape: circle
    style.fill: "#8ac926"
  }
  jackOut1: {
    shape: circle
    style.fill: "#bf0603"
  }
  jackOut2: {
    shape: circle
    style.fill: "#bf0603"
  }
  jackOut3: {
    shape: circle
    style.fill: "#bf0603"
  }
  jackOut4: {
    shape: circle
    style.fill: "#bf0603"
  }
  jackOut5: {
    shape: circle
    style.fill: "#bf0603"
  }
  jackOut6: {
    shape: circle
    style.fill: "#bf0603"
  }
  shape: rectangle
  style.fill: "#00afb9"
}

usbkey: {
  recL: {
    shape: circle
    style.fill: "#8ac926"
  }
  recR: {
    shape: circle
    style.fill: "#8ac926"
  }
  playL: {
    shape: circle
    style.fill: "#bf0603"
  }
  playR: {
    shape: circle
    style.fill: "#bf0603"
  }
  shape: rectangle
  style.fill: "#f07167"
}

# some minimal connectors

console: {
  ch1.label: canale_uno
  bus1: {
    label: bus_uno
    style.fill: "#ffb703"
  }
}

phisicalInput.block1-8: {
  xlr1: {
    shape: circle
    style.fill: "#8ac926"
  }
  xlr2: {
    shape: circle
    style.fill: "#8ac926"
  }
}

xusb.block1-8: {
  return1: {
    shape: circle
    style.fill: "#8ac926"
  }

  send1: {
    shape: circle
    style.fill: "#bf0603"
  }
}

internalInput.block1-8: {
  ch1: {
    shape: circle
    style.fill: "#a0a0a0"
  }
}

internalOutput.block1-8: {
  ch1: {
    shape: circle
    style.fill: "#a0a0a0"
  }
}

# end
direction:left
console.STEREO->console.M: mono depends on LR
direction:down
phisicalInput.block1-8.xlr1{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block1-8.ch1{
 shape: circle
 style.fill: '#a0a0a0'
}

phisicalInput.block1-8.xlr1 -> internalInput.block1-8.ch1
phisicalInput.block1-8.xlr2{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block1-8.ch2{
 shape: circle
 style.fill: '#a0a0a0'
}

phisicalInput.block1-8.xlr2 -> internalInput.block1-8.ch2
phisicalInput.block1-8.xlr3{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block1-8.ch3{
 shape: circle
 style.fill: '#a0a0a0'
}

phisicalInput.block1-8.xlr3 -> internalInput.block1-8.ch3
phisicalInput.block1-8.xlr4{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block1-8.ch4{
 shape: circle
 style.fill: '#a0a0a0'
}

phisicalInput.block1-8.xlr4 -> internalInput.block1-8.ch4
phisicalInput.block1-8.xlr5{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block1-8.ch5{
 shape: circle
 style.fill: '#a0a0a0'
}

phisicalInput.block1-8.xlr5 -> internalInput.block1-8.ch5
phisicalInput.block1-8.xlr6{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block1-8.ch6{
 shape: circle
 style.fill: '#a0a0a0'
}

phisicalInput.block1-8.xlr6 -> internalInput.block1-8.ch6
phisicalInput.block1-8.xlr7{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block1-8.ch7{
 shape: circle
 style.fill: '#a0a0a0'
}

phisicalInput.block1-8.xlr7 -> internalInput.block1-8.ch7
phisicalInput.block1-8.xlr8{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block1-8.ch8{
 shape: circle
 style.fill: '#a0a0a0'
}

phisicalInput.block1-8.xlr8 -> internalInput.block1-8.ch8
phisicalInput.block9-16.xlr9{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block9-16.ch9{
 shape: circle
 style.fill: '#a0a0a0'
}

phisicalInput.block9-16.xlr9 -> internalInput.block9-16.ch9
phisicalInput.block9-16.xlr10{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block9-16.ch10{
 shape: circle
 style.fill: '#a0a0a0'
}

phisicalInput.block9-16.xlr10 -> internalInput.block9-16.ch10
phisicalInput.block9-16.xlr11{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block9-16.ch11{
 shape: circle
 style.fill: '#a0a0a0'
}

phisicalInput.block9-16.xlr11 -> internalInput.block9-16.ch11
phisicalInput.block9-16.xlr12{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block9-16.ch12{
 shape: circle
 style.fill: '#a0a0a0'
}

phisicalInput.block9-16.xlr12 -> internalInput.block9-16.ch12
phisicalInput.block9-16.xlr13{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block9-16.ch13{
 shape: circle
 style.fill: '#a0a0a0'
}

phisicalInput.block9-16.xlr13 -> internalInput.block9-16.ch13
phisicalInput.block9-16.xlr14{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block9-16.ch14{
 shape: circle
 style.fill: '#a0a0a0'
}

phisicalInput.block9-16.xlr14 -> internalInput.block9-16.ch14
phisicalInput.block9-16.xlr15{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block9-16.ch15{
 shape: circle
 style.fill: '#a0a0a0'
}

phisicalInput.block9-16.xlr15 -> internalInput.block9-16.ch15
phisicalInput.block9-16.xlr16{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block9-16.ch16{
 shape: circle
 style.fill: '#a0a0a0'
}

phisicalInput.block9-16.xlr16 -> internalInput.block9-16.ch16
xusb.block17-24.return17{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block17-24.ch17{
 shape: circle
 style.fill: '#a0a0a0'
}

xusb.block17-24.return17 -> internalInput.block17-24.ch17
xusb.block17-24.return18{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block17-24.ch18{
 shape: circle
 style.fill: '#a0a0a0'
}

xusb.block17-24.return18 -> internalInput.block17-24.ch18
xusb.block17-24.return19{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block17-24.ch19{
 shape: circle
 style.fill: '#a0a0a0'
}

xusb.block17-24.return19 -> internalInput.block17-24.ch19
xusb.block17-24.return20{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block17-24.ch20{
 shape: circle
 style.fill: '#a0a0a0'
}

xusb.block17-24.return20 -> internalInput.block17-24.ch20
xusb.block17-24.return21{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block17-24.ch21{
 shape: circle
 style.fill: '#a0a0a0'
}

xusb.block17-24.return21 -> internalInput.block17-24.ch21
xusb.block17-24.return22{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block17-24.ch22{
 shape: circle
 style.fill: '#a0a0a0'
}

xusb.block17-24.return22 -> internalInput.block17-24.ch22
xusb.block17-24.return23{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block17-24.ch23{
 shape: circle
 style.fill: '#a0a0a0'
}

xusb.block17-24.return23 -> internalInput.block17-24.ch23
xusb.block17-24.return24{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block17-24.ch24{
 shape: circle
 style.fill: '#a0a0a0'
}

xusb.block17-24.return24 -> internalInput.block17-24.ch24
xusb.block25-32.return25{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block25-32.ch25{
 shape: circle
 style.fill: '#a0a0a0'
}

xusb.block25-32.return25 -> internalInput.block25-32.ch25
xusb.block25-32.return26{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block25-32.ch26{
 shape: circle
 style.fill: '#a0a0a0'
}

xusb.block25-32.return26 -> internalInput.block25-32.ch26
xusb.block25-32.return27{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block25-32.ch27{
 shape: circle
 style.fill: '#a0a0a0'
}

xusb.block25-32.return27 -> internalInput.block25-32.ch27
xusb.block25-32.return28{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block25-32.ch28{
 shape: circle
 style.fill: '#a0a0a0'
}

xusb.block25-32.return28 -> internalInput.block25-32.ch28
xusb.block25-32.return29{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block25-32.ch29{
 shape: circle
 style.fill: '#a0a0a0'
}

xusb.block25-32.return29 -> internalInput.block25-32.ch29
xusb.block25-32.return30{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block25-32.ch30{
 shape: circle
 style.fill: '#a0a0a0'
}

xusb.block25-32.return30 -> internalInput.block25-32.ch30
xusb.block25-32.return31{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block25-32.ch31{
 shape: circle
 style.fill: '#a0a0a0'
}

xusb.block25-32.return31 -> internalInput.block25-32.ch31
xusb.block25-32.return32{
 shape: circle
 style.fill: '#8ac926'
}

internalInput.block25-32.ch32{
 shape: circle
 style.fill: '#a0a0a0'
}

xusb.block25-32.return32 -> internalInput.block25-32.ch32
console.ch1{
 label:1.Lav1
}

internalInput.block1-8.ch1 -> console.ch1
console.STEREO.L
console.ch1 -> console.STEREO.L
console.bus1{
 label:1.
}

console.ch1 -> console.bus1
console.ch2{
 label:2.Lav2
}

internalInput.block1-8.ch2 -> console.ch2
console.ch2 -> console.STEREO.L
console.ch2 -> console.bus1
console.ch3{
 label:3.Lav3
}

internalInput.block1-8.ch3 -> console.ch3
console.ch3 -> console.STEREO.L
console.ch3 -> console.bus1
console.ch4{
 label:4.Gelato
}

internalInput.block1-8.ch4 -> console.ch4
console.ch4 -> console.STEREO.L
console.ch4 -> console.bus1
console.ch5{
 label:5.Amb1
}

internalInput.block1-8.ch5 -> console.ch5
console.ch5 -> console.STEREO.L
console.ch5 -> console.bus1
console.ch6{
 label:6.Amb2
}

internalInput.block1-8.ch6 -> console.ch6
console.ch6 -> console.STEREO.L
console.ch6 -> console.bus1
console.ch7{
 label:7.Scorta1
}

internalInput.block1-8.ch7 -> console.ch7
console.ch7 -> console.STEREO.L
console.ch7 -> console.bus1
console.ch8{
 label:8.Scorta2
}

internalInput.block1-8.ch8 -> console.ch8
console.ch8 -> console.STEREO.L
console.ch8 -> console.bus1
console.ch9{
 label:9.Lat_L
}

internalInput.block9-16.ch9 -> console.ch9
console.ch9 -> console.bus1
console.ch10{
 label:10.Stereo_L
}

internalInput.block9-16.ch10 -> console.ch10
console.ch10 -> console.bus1
console.ch11{
 label:11.Stereo_R
}

internalInput.block9-16.ch11 -> console.ch11
console.ch11 -> console.bus1
console.ch12{
 label:12.Lat_R
}

internalInput.block9-16.ch12 -> console.ch12
console.ch12 -> console.bus1
usbkey.playL->console.ch13
console.ch13{
 label:13.USB_L
}

console.ch13 -> console.STEREO.L
console.ch13 -> console.bus1
usbkey.playR->console.ch14
console.ch14{
 label:14.USB_R
}

console.ch14 -> console.STEREO.L
console.ch14 -> console.bus1
console.ch15{
 label:15.PC_L
}

internalInput.block25-32.ch25 -> console.ch15
console.ch15 -> console.STEREO.L
console.ch15 -> console.bus1
console.ch16{
 label:16.PC_R
}

internalInput.block25-32.ch26 -> console.ch16
console.ch16 -> console.STEREO.L
console.ch16 -> console.bus1
internalOutput.block1-8.ch1{
 shape: circle
 style.fill: '#a0a0a0'
}

console.bus1 -> internalOutput.block1-8.ch1
internalOutput.block1-8.ch2{
 shape: circle
 style.fill: '#a0a0a0'
}

internalOutput.block1-8.ch3{
 shape: circle
 style.fill: '#a0a0a0'
}

internalOutput.block1-8.ch4{
 shape: circle
 style.fill: '#a0a0a0'
}

internalOutput.block1-8.ch5{
 shape: circle
 style.fill: '#a0a0a0'
}

internalOutput.block1-8.ch6{
 shape: circle
 style.fill: '#a0a0a0'
}

console.M -> internalOutput.block1-8.ch6
internalOutput.block1-8.ch7{
 shape: circle
 style.fill: '#a0a0a0'
}

console.STEREO.L -> internalOutput.block1-8.ch7
internalOutput.block1-8.ch8{
 shape: circle
 style.fill: '#a0a0a0'
}

console.STEREO.R -> internalOutput.block1-8.ch8
internalOutput.block9-16.ch9{
 shape: circle
 style.fill: '#a0a0a0'
}

internalOutput.block9-16.ch10{
 shape: circle
 style.fill: '#a0a0a0'
}

internalOutput.block9-16.ch11{
 shape: circle
 style.fill: '#a0a0a0'
}

internalOutput.block9-16.ch12{
 shape: circle
 style.fill: '#a0a0a0'
}

internalOutput.block9-16.ch13{
 shape: circle
 style.fill: '#a0a0a0'
}

internalOutput.block9-16.ch14{
 shape: circle
 style.fill: '#a0a0a0'
}

internalOutput.block9-16.ch15{
 shape: circle
 style.fill: '#a0a0a0'
}

internalOutput.block9-16.ch16{
 shape: circle
 style.fill: '#a0a0a0'
}

