# macro blocks

direction: right

classes: {
  slider_class: {
    width: 100
    height: 200
    style: {
      stroke-width: 0
      fill: "#44C7B1"
      shadow: true
      border-radius: 5
    }
  }
}

PHISICAL: {
  shape: square
  xlrPanel: {
    shape: rectangle
    style: {
      fill: RoyalBlue
      font-color: black
    }
    femaleXLR: {
      style.fill: LawnGreen
    }
    maleXLR: {
      shape: rectangle
      style: {
        fill: red
        font-color: white
      }
    }
  }

  auxPanel: {
    shape: rectangle
    style: {
      fill: RoyalBlue
      font-color: black
    }
    outTRS: {
      style: {
        fill: red
        font-color: white
      }
    }
    inTRS: {
      style.fill: LawnGreen
    }
  }

  usbKey: {
    shape: rectangle
    style: {
      fill: RoyalBlue
      font-color: black
    }
    rec: {
      style: {
        fill: red
        font-color: white
      }
    }
    play: {
      style.fill: LawnGreen
    }
  }

  xusbCard: {
    style: {
      fill: RoyalBlue
      font-color: black
    }
    send: {
      style: {
        fill: red
        font-color: white
      }
    }
    return: {
      style.fill: LawnGreen
    }
  }
}

console: {
  label: CONSOLE (sliders and buses)
  shape: parallelogram
  style.fill: "#ffe5d9"
}


# trying to build slider 01
# first time for slider 01
#setName: ch__01
#setName: Bolla 
PHISICAL.xlrPanel.femaleXlr.in1 -> console.ch01
# trying to build slider 01
console.ch01 -> console.bus1
# trying to build slider 01
console.ch01 -> console.bus2
# trying to build slider 02
# first time for slider 02
#setName: ch__02
#setName: Acustica 
PHISICAL.xlrPanel.femaleXlr.in2 -> console.ch02
# trying to build slider 02
console.ch02 -> console.bus1
# trying to build slider 02
console.ch02 -> console.bus2
# trying to build slider 03
# first time for slider 03
#setName: ch__03
#setName: Alberto 
PHISICAL.xlrPanel.femaleXlr.in3 -> console.ch03
# trying to build slider 03
console.ch03 -> console.bus1
# trying to build slider 03
console.ch03 -> console.bus2
# trying to build slider 04
# first time for slider 04
#setName: ch__04
#setName: Folk 
PHISICAL.xlrPanel.femaleXlr.in4 -> console.ch04
# trying to build slider 04
console.ch04 -> console.bus1
# trying to build slider 04
console.ch04 -> console.bus2
# trying to build slider 05
# first time for slider 05
#setName: ch__05
#setName: Classica 
PHISICAL.xlrPanel.femaleXlr.in5 -> console.ch05
# trying to build slider 05
console.ch05 -> console.bus1
# trying to build slider 05
console.ch05 -> console.bus2
# trying to build slider 06
# first time for slider 06
#setName: ch__06
#setName: 12Corde 
PHISICAL.xlrPanel.femaleXlr.in6 -> console.ch06
# trying to build slider 06
console.ch06 -> console.bus1
# trying to build slider 06
console.ch06 -> console.bus2
# trying to build slider 07
# first time for slider 07
#setName: ch__07
#setName: Sax 
PHISICAL.xlrPanel.femaleXlr.in7 -> console.ch07
# trying to build slider 07
console.ch07 -> console.bus1
# trying to build slider 07
console.ch07 -> console.bus2
# trying to build slider 08
# first time for slider 08
#setName: ch__08
#setName: Flauto 
PHISICAL.xlrPanel.femaleXlr.in8 -> console.ch08
# trying to build slider 08
console.ch08 -> console.bus1
# trying to build slider 08
console.ch08 -> console.bus2
# trying to build slider 09
# first time for slider 09
#setName: ch__09
#setName: Tast L 
PHISICAL.xlrPanel.femaleXlr.in9 -> console.ch09
# trying to build slider 09
console.ch09 -> console.bus1
# trying to build slider 09
console.ch09 -> console.bus2
# trying to build slider 10
# first time for slider 10
#setName: ch__10
#setName: Tast R 
PHISICAL.xlrPanel.femaleXlr.in10 -> console.ch10
# trying to build slider 10
console.ch10 -> console.bus1
# trying to build slider 10
console.ch10 -> console.bus2
# trying to build slider 11
# first time for slider 11
#setName: ch__11
#setName: TomL 
PHISICAL.xlrPanel.femaleXlr.in11 -> console.ch11
# trying to build slider 11
console.ch11 -> console.bus1
# trying to build slider 11
console.ch11 -> console.bus2
# trying to build slider 12
# first time for slider 12
#setName: ch__12
#setName: TomR 
PHISICAL.xlrPanel.femaleXlr.in12 -> console.ch12
# trying to build slider 12
console.ch12 -> console.bus1
# trying to build slider 12
console.ch12 -> console.bus2
# trying to build slider 13
# first time for slider 13
#setName: ch__13
#setName: Cassa 
PHISICAL.xlrPanel.femaleXlr.in13 -> console.ch13
# trying to build slider 13
console.ch13 -> console.bus1
# trying to build slider 13
console.ch13 -> console.bus2
# trying to build slider 14
# first time for slider 14
#setName: ch__14
#setName: Snare 
PHISICAL.xlrPanel.femaleXlr.in14 -> console.ch14
# trying to build slider 14
console.ch14 -> console.bus1
# trying to build slider 14
console.ch14 -> console.bus2
# trying to build slider 15
# first time for slider 15
#setName: ch__15
#setName: Bruno 
PHISICAL.xlrPanel.femaleXlr.in15 -> console.ch15
# trying to build slider 15
console.ch15 -> console.bus1
# trying to build slider 15
console.ch15 -> console.bus2
# trying to build slider 16
# first time for slider 16
#setName: ch__16
#setName: scorta 
PHISICAL.xlrPanel.femaleXlr.in16 -> console.ch16
# trying to build slider 16
console.ch16 -> console.bus1
# trying to build slider 16
console.ch16 -> console.bus2
# trying to build slider 17
# first time for slider 17
#setName: ch__17
console.ch17 -> console.bus1
# trying to build slider 17
console.ch17 -> console.bus2
# trying to build slider 18
# first time for slider 18
#setName: ch__18
console.ch18 -> console.bus1
# trying to build slider 18
console.ch18 -> console.bus2
# trying to build slider 19
# first time for slider 19
#setName: ch__19
#setName: BasiL 
PHISICAL.xusbCard.return.ch31 -> console.ch19
# trying to build slider 19
console.ch19 -> console.bus1
# trying to build slider 19
console.ch19 -> console.bus2
# trying to build slider 20
# first time for slider 20
#setName: ch__20
#setName: BasiR 
PHISICAL.xusbCard.return.ch32 -> console.ch20
# trying to build slider 20
console.ch20 -> console.bus1
# trying to build slider 20
console.ch20 -> console.bus2
# trying to build slider 21
# first time for slider 21
#setName: ch__21
#setName:  
PHISICAL.xusbCard.return.ch21 -> console.ch21
# trying to build slider 21
console.ch21 -> console.bus1
# trying to build slider 21
console.ch21 -> console.bus2
# trying to build slider 22
# first time for slider 22
#setName: ch__22
#setName:  
PHISICAL.xusbCard.return.ch22 -> console.ch22
# trying to build slider 22
console.ch22 -> console.bus1
# trying to build slider 22
console.ch22 -> console.bus2
# trying to build slider 23
# first time for slider 23
#setName: ch__23
#setName:  
PHISICAL.xusbCard.return.ch23 -> console.ch23
# trying to build slider 23
console.ch23 -> console.bus1
# trying to build slider 23
console.ch23 -> console.bus2
# trying to build slider 24
# first time for slider 24
#setName: ch__24
#setName:  
PHISICAL.xusbCard.return.ch24 -> console.ch24
# trying to build slider 24
console.ch24 -> console.bus1
# trying to build slider 24
console.ch24 -> console.bus2
# trying to build slider 25
# first time for slider 25
#setName: ch__25
#setName:  
PHISICAL.xusbCard.return.ch25 -> console.ch25
# trying to build slider 25
console.ch25 -> console.bus1
# trying to build slider 25
console.ch25 -> console.bus2
# trying to build slider 26
# first time for slider 26
#setName: ch__26
#setName:  
PHISICAL.xusbCard.return.ch26 -> console.ch26
# trying to build slider 26
console.ch26 -> console.bus1
# trying to build slider 26
console.ch26 -> console.bus2
# trying to build slider 27
# first time for slider 27
#setName: ch__27
#setName:  
PHISICAL.xusbCard.return.ch27 -> console.ch27
# trying to build slider 27
console.ch27 -> console.bus1
# trying to build slider 27
console.ch27 -> console.bus2
# trying to build slider 28
# first time for slider 28
#setName: ch__28
#setName:  
PHISICAL.xusbCard.return.ch28 -> console.ch28
# trying to build slider 28
console.ch28 -> console.bus1
# trying to build slider 28
console.ch28 -> console.bus2
# trying to build slider 29
# first time for slider 29
#setName: ch__29
#setName:  
PHISICAL.xusbCard.return.ch29 -> console.ch29
# trying to build slider 29
console.ch29 -> console.bus1
# trying to build slider 29
console.ch29 -> console.bus2
# trying to build slider 30
# first time for slider 30
#setName: ch__30
#setName:  
PHISICAL.xusbCard.return.ch30 -> console.ch30
# trying to build slider 30
console.ch30 -> console.bus1
# trying to build slider 30
console.ch30 -> console.bus2
# trying to build slider 31
# first time for slider 31
#setName: ch__31
#setName:  
PHISICAL.xusbCard.return.ch31 -> console.ch31
# trying to build slider 31
console.ch31 -> console.bus1
# trying to build slider 31
console.ch31 -> console.bus2
# trying to build slider 32
# first time for slider 32
#setName: ch__32
#setName:  
PHISICAL.xusbCard.return.ch32 -> console.ch32
# trying to build slider 32
console.ch32 -> console.bus1
# trying to build slider 32
console.ch32 -> console.bus2
# printing all created elements
PHISICAL.xlrPanel.femaleXlr.in3: {
	shape: circle
	style.fill: white
}
console.ch22
PHISICAL.xlrPanel.femaleXlr.in9: {
	shape: circle
	style.fill: white
}
console.ch25
console.ch31
console.ch09
PHISICAL.xusbCard.return.ch20: {
	shape: circle
	style.fill: white
}
console.ch08
PHISICAL.xusbCard.return.ch32: {
	shape: circle
	style.fill: white
}
PHISICAL.xlrPanel.femaleXlr.in4: {
	shape: circle
	style.fill: white
}
console.ch13
PHISICAL.xlrPanel.femaleXlr.in1: {
	shape: circle
	style.fill: white
}
console.ch14
console.ch21
console.bus4: {
	label: SoloL
	shape: square
}
console.ch27
console.bus3: {
	label: Mono
	shape: square
}
console.ch26
console.ch32
PHISICAL.xlrPanel.femaleXlr.in2: {
	shape: circle
	style.fill: white
}
console.ch23
PHISICAL.xusbCard.return.ch21: {
	shape: circle
	style.fill: white
}
console.bus1: {
	label: MainL
	shape: square
}
console.ch24
console.ch16
PHISICAL.xlrPanel.femaleXlr.in13: {
	shape: circle
	style.fill: white
}
console.ch11
console.bus109: {
	label: MixBus 9
	shape: square
}
console.ch17
PHISICAL.xlrPanel.femaleXlr.in14: {
	shape: circle
	style.fill: white
}
PHISICAL.xusbCard.return.ch31: {
	shape: circle
	style.fill: white
}
console.ch12
console.ch15
console.bus5: {
	label: SoloR
	shape: square
}
PHISICAL.xlrPanel.femaleXlr.in10: {
	shape: circle
	style.fill: white
}
console.bus2: {
	label: MainR
	shape: square
}
PHISICAL.xusbCard.return.ch19: {
	shape: circle
	style.fill: white
}
PHISICAL.xlrPanel.femaleXlr.in8: {
	shape: circle
	style.fill: white
}
console.bus110: {
	label: MixBus 10
	shape: square
}
PHISICAL.xusbCard.return.ch30: {
	shape: circle
	style.fill: white
}
PHISICAL.xusbCard.return.ch17: {
	shape: circle
	style.fill: white
}
console.ch20
console.ch19
console.bus113: {
	label: MixBus 13
	shape: square
}
console.bus103: {
	label: MixBus 3
	shape: square
}
console.ch18
PHISICAL.xusbCard.return.ch25: {
	shape: circle
	style.fill: white
}
PHISICAL.xusbCard.return.ch29: {
	shape: circle
	style.fill: white
}
PHISICAL.xlrPanel.femaleXlr.in11: {
	shape: circle
	style.fill: white
}
PHISICAL.xlrPanel.femaleXlr.in16: {
	shape: circle
	style.fill: white
}
console.bus102: {
	label: MixBus 2
	shape: square
}
console.ch04
console.ch03
PHISICAL.xlrPanel.femaleXlr.in7: {
	shape: circle
	style.fill: white
}
console.bus112: {
	label: MixBus 12
	shape: square
}
PHISICAL.xusbCard.return.ch22: {
	shape: circle
	style.fill: white
}
PHISICAL.xlrPanel.femaleXlr.in15: {
	shape: circle
	style.fill: white
}
PHISICAL.xlrPanel.femaleXlr.in5: {
	shape: circle
	style.fill: white
}
console.ch30
PHISICAL.xusbCard.return.ch24: {
	shape: circle
	style.fill: white
}
console.bus105: {
	label: MixBus 5
	shape: square
}
PHISICAL.xusbCard.return.ch27: {
	shape: circle
	style.fill: white
}
console.ch06
console.ch07
PHISICAL.xlrPanel.femaleXlr.in12: {
	shape: circle
	style.fill: white
}
console.ch01
console.ch29
console.bus101: {
	label: MixBus 1
	shape: square
}
PHISICAL.xusbCard.return.ch23: {
	shape: circle
	style.fill: white
}
console.bus104: {
	label: MixBus 4
	shape: square
}
console.ch05
PHISICAL.xlrPanel.femaleXlr.in6: {
	shape: circle
	style.fill: white
}
console.ch10
console.ch02
console.bus114: {
	label: MixBus 14
	shape: square
}
PHISICAL.xusbCard.return.ch26: {
	shape: circle
	style.fill: white
}
PHISICAL.xusbCard.return.ch28: {
	shape: circle
	style.fill: white
}
PHISICAL.xusbCard.return.ch18: {
	shape: circle
	style.fill: white
}
console.bus111: {
	label: MixBus 11
	shape: square
}
console.ch28
