# internal input & output, configuration screens, logical connection with macroblocks

VIRTUAL: {
  shape: square

  internalInput: {
    shape: step
    style.fill: LawnGreen
  }

  internalOutput: {
    shape: step
    style: {
      fill: red
      font-color: white
    }
  }
}

# GUI for I/O configurations

Inputs screen: {
  shape: page
  style: {
    fill: grey
    font-color: white
  }
}

Channel input dropdown: {
  shape: page
  style: {
    fill: grey
    font-color: white
  }
}

Card screen: {
  shape: page
  style: {
    fill: grey
    font-color: white
  }
}

Out 1-16 screen: {
  shape: page
  style: {
    fill: grey
    font-color: white
  }
}

Aux Out screen: {
  shape: page
  style: {
    fill: grey
    font-color: white
  }
}

Card screen: {
  shape: page
  style: {
    fill: grey
    font-color: white
  }
}

XLR screen: {
  shape: page
  style: {
    fill: grey
    font-color: white
  }
}

dedicated GUI: {
  shape: page
  style: {
    fill: grey
    font-color: white
  }
}

# connections between macro blocks
PHISICAL.xlrPanel.femaleXLR -> Inputs screen: {
  style: {
    stroke: orange
  }
}
PHISICAL.xusbCard.return -> Inputs screen: {
  style: {
    stroke: orange
  }
}
Inputs screen -> VIRTUAL.internalInput

PHISICAL.auxPanel.inTRS -> Channel input dropdown: {
  style: {
    stroke: orange
  }
}
PHISICAL.usbKey.play -> Channel input dropdown: {
  style: {
    stroke: orange
  }
}
VIRTUAL.internalInput -> Channel input dropdown: {
  style: {
    stroke: orange
  }
}
Channel input dropdown -> console

console -> Out 1-16 screen: {
  style: {
    stroke: orange
  }
}
Out 1-16 screen -> VIRTUAL.internalOutput

console -> Aux Out screen: {
  style: {
    stroke: orange
  }
}
Aux Out screen -> PHISICAL.auxPanel.outTRS

PHISICAL.xlrPanel.femaleXLR -> XLR screen: {
  style: {
    stroke: orange
  }
}
PHISICAL.xusbCard.return -> XLR screen: {
  style: {
    stroke: orange
  }
}
VIRTUAL.internalOutput -> XLR screen: {
  style: {
    stroke: orange
  }
}
XLR screen -> PHISICAL.xlrPanel.maleXLR

PHISICAL.xlrPanel.femaleXLR -> Card screen: {
  style: {
    stroke: orange
  }
}
VIRTUAL.internalOutput -> Card screen: {
  style: {
    stroke: orange
  }
}
Card screen -> PHISICAL.xusbCard.send

console -> dedicated GUI: {
  style: {
    stroke: orange
  }
}
dedicated GUI -> PHISICAL.usbKey.rec

