# macro blocks

direction: right

classes: {
  slider_class: {
    width: 100
    height: 200
    style: {
      stroke-width: 0
      fill: "#44C7B1"
      shadow: true
      border-radius: 5
    }
  }
}

PHISICAL: {
  shape: square
  xlrPanel: {
    shape: rectangle
    style: {
      fill: RoyalBlue
      font-color: black
    }
    femaleXLR: {
      style.fill: LawnGreen
    }
    maleXLR: {
      shape: rectangle
      style: {
        fill: red
        font-color: white
      }
    }
  }

  auxPanel: {
    shape: rectangle
    style: {
      fill: RoyalBlue
      font-color: black
    }
    outTRS: {
      style: {
        fill: red
        font-color: white
      }
    }
    inTRS: {
      style.fill: LawnGreen
    }
  }

  usbKey: {
    shape: rectangle
    style: {
      fill: RoyalBlue
      font-color: black
    }
    rec: {
      style: {
        fill: red
        font-color: white
      }
    }
    play: {
      style.fill: LawnGreen
    }
  }

  xusbCard: {
    style: {
      fill: RoyalBlue
      font-color: black
    }
    send: {
      style: {
        fill: red
        font-color: white
      }
    }
    return: {
      style.fill: LawnGreen
    }
  }
}

console: {
  label: CONSOLE (sliders and buses)
  shape: parallelogram
  style.fill: "#ffe5d9"
}


