# fixed hardware (display always)

direction:down

console: {
  SOLO.style.fill: "#ffff3f"
  M.style.fill: "#8ecae6"
  STEREO:{
    L
    R
    style.fill: "#8ecae6"
    }
  shape: parallelogram
  style.fill: "#ffe5d9"
}

local:{
  block1-8.shape:cloud
  block9-16.shape:cloud
  block17-24.shape:cloud
  block25-32.shape:cloud
  style.fill: "#00afb9"
}

output: {
  xlr1: {
    shape: circle
    style.fill: "#bf0603"
  }
  xlr2: {
    shape: circle
    style.fill: "#bf0603"
  }
  xlr3: {
    shape: circle
    style.fill: "#bf0603"
  }
  xlr4: {
    shape: circle
    style.fill: "#bf0603"
  }
  xlr5: {
    shape: circle
    style.fill: "#bf0603"
  }
  xlr6: {
    shape: circle
    style.fill: "#bf0603"
  }
  xlr7: {
    shape: circle
    style.fill: "#bf0603"
  }
  xlr8: {
    shape: circle
    style.fill: "#bf0603"
  }
  shape: rectangle
  style.fill: "#00afb9"

}

xusb:{
  block1-8.shape:cloud
  block9-16.shape:cloud
  block17-24.shape:cloud
  block25-32.shape:cloud
  style.fill: "#f07167"
}

aux: {
  jack_in1: {
    shape: circle
    style.fill: "#8ac926"
  }
  jack_in2: {
    shape: circle
    style.fill: "#8ac926"
  }
  jack_in3: {
    shape: circle
    style.fill: "#8ac926"
  }
  jack_in4: {
    shape: circle
    style.fill: "#8ac926"
  }
  jack_in5: {
    shape: circle
    style.fill: "#8ac926"
  }
  jack_in6: {
    shape: circle
    style.fill: "#8ac926"
  }
  jack_out1: {
    shape: circle
    style.fill: "#bf0603"
    
  }
  jack_out2: {
    shape: circle
    style.fill: "#bf0603"
  }
  jack_out3: {
    shape: circle
    style.fill: "#bf0603"
  }
  jack_out4: {
    shape: circle
    style.fill: "#bf0603"
  }
  jack_out5: {
    shape: circle
    style.fill: "#bf0603"
  }
  jack_out6: {
    shape: circle
    style.fill: "#bf0603"
  } 
  shape: rectangle
  style.fill: "#00afb9"
}


usbkey: {
  recL: {
    shape: circle
    style.fill: "#8ac926"
  }
  recR: {
    shape: circle
    style.fill: "#8ac926"
  }
  playL: {
    shape: circle
    style.fill: "#bf0603"
  }
  playR: {
    shape: circle
    style.fill: "#bf0603"
  }
  shape: rectangle
}


# some minimal connectors

console: {
  slider1.label:ch1
  bus1:{
    label:MixBus1
    style.fill: "#ffb703"
  }
}

local.block1-8: {
  xlr1: {
    shape: circle
    style.fill: "#8ac926"
  }
  xlr2: {
    shape: circle
    style.fill: "#8ac926"
  }
}

xusb.block1-8: {
    return1: {
      shape: circle
      style.fill: "#8ac926"
    }
   
    send1: {
      shape: circle
      style.fill: "#bf0603"
    }
   
   
}
direction:left
console.STEREO->console.M: mono depends on LR
console.slider1.label: Lav1
local.block1-8.xlr1: {
shape: circle
style.fill: '#8ac926'
}
local.block1-8.xlr1->console.slider1
console.slider1 -> console.STEREO
console.slider1 -> console.bus1
console.slider2.label: Lav2
local.block1-8.xlr2: {
shape: circle
style.fill: '#8ac926'
}
local.block1-8.xlr2->console.slider2
console.slider2 -> console.STEREO
console.slider2 -> console.bus1
console.slider3.label: Lav3
local.block1-8.xlr3: {
shape: circle
style.fill: '#8ac926'
}
local.block1-8.xlr3->console.slider3
console.slider3 -> console.STEREO
console.slider3 -> console.bus1
console.slider4.label: Gelato
local.block1-8.xlr4: {
shape: circle
style.fill: '#8ac926'
}
local.block1-8.xlr4->console.slider4
console.slider4 -> console.STEREO
console.slider4 -> console.bus1
console.slider5.label: Amb1
local.block1-8.xlr5: {
shape: circle
style.fill: '#8ac926'
}
local.block1-8.xlr5->console.slider5
console.slider5 -> console.STEREO
console.slider5 -> console.bus1
console.slider6.label: Amb2
local.block1-8.xlr6: {
shape: circle
style.fill: '#8ac926'
}
local.block1-8.xlr6->console.slider6
console.slider6 -> console.STEREO
console.slider6 -> console.bus1
console.slider7.label: Scorta1
local.block1-8.xlr7: {
shape: circle
style.fill: '#8ac926'
}
local.block1-8.xlr7->console.slider7
console.slider7 -> console.STEREO
console.slider7 -> console.bus1
console.slider8.label: Scorta2
local.block1-8.xlr8: {
shape: circle
style.fill: '#8ac926'
}
local.block1-8.xlr8->console.slider8
console.slider8 -> console.STEREO
console.slider8 -> console.bus1
console.slider9.label: Lat_L
local.block9-16.xlr9: {
shape: circle
style.fill: '#8ac926'
}
local.block9-16.xlr9->console.slider9
console.slider9 -> console.bus1
console.slider10.label: Stereo_L
local.block9-16.xlr10: {
shape: circle
style.fill: '#8ac926'
}
local.block9-16.xlr10->console.slider10
console.slider10 -> console.bus1
console.slider11.label: Stereo_R
local.block9-16.xlr11: {
shape: circle
style.fill: '#8ac926'
}
local.block9-16.xlr11->console.slider11
console.slider11 -> console.bus1
console.slider12.label: Lat_R
local.block9-16.xlr12: {
shape: circle
style.fill: '#8ac926'
}
local.block9-16.xlr12->console.slider12
console.slider12 -> console.bus1
console.slider13.label: USB_L
usbkey.playL->console.slider13
console.slider13 -> console.STEREO
console.slider13 -> console.bus1
console.slider14.label: USB_R
usbkey.playR->console.slider14
console.slider14 -> console.STEREO
console.slider14 -> console.bus1
console.slider15.label: PC_L
xusb.block25-32.return25: {
shape: circle
style.fill: '#8ac926'
}
xusb.block25-32.return25->console.slider15
console.slider15 -> console.STEREO
console.slider15 -> console.bus1
console.slider16.label: PC_R
xusb.block25-32.return26: {
shape: circle
style.fill: '#8ac926'
}
xusb.block25-32.return26->console.slider16
console.slider16 -> console.STEREO
console.slider16 -> console.bus1
console.bus1 -> output.xlr1
console.M -> output.xlr6
console.STEREO.L -> output.xlr7
console.STEREO.R -> output.xlr8
