console.ch3 {label: cello} 
console.M

console.ch3 -> console.M


dario {
    label: "marini"
    style.fill: "#ffff3f"
}

dario <-> console.ch3 -> pippo
phisicalInput.block9-16.xlr12{
    shape: circle
    style.fill: '#8ac926'
   }
   
   phisicalInput.block9-16.xlr12{
    shape: circle
    style.fill: '#8ac926'
   }
   
   phisicalOutput.block1-4.xlr1{
    shape: circle
    style.fill: '#bf0603'
   }
   