
# x32 description

console: {
  slider1.label:ch1
  slider2.label:ch2
  slider3.label:ch3
  slider4.label:ch4
  slider5.label:ch5
  slider6.label:ch6
  slider7.label:ch7
  slider8.label:ch8
  slider9.label:ch9
  slider10.label:ch10
  slider11.label:ch11
  slider12.label:ch12
  slider13.label:ch13
  slider14.label:ch14
  slider15.label:ch15
  slider16.label:ch16
  bus1:{
    label:MixBus1
    style.fill: "#ffb703"
    }
  bus2:{
    label:MixBus2
    style.fill: "#ffb703"
    }
  bus3:{
    label:MixBus3
    style.fill: "#ffb703"
    }
  bus4:{
    label:MixBus4
    style.fill: "#ffb703"
  }
  bus5:{
    label:MixBus5
    style.fill: "#ffb703"
  }
  bus6:{
    label:MixBus6
    style.fill: "#ffb703"
  }
  SOLO.style.fill: "#ffff3f"
  M.style.fill: "#8ecae6"
  LR.style.fill: "#8ecae6"
  shape: parallelogram
  style.fill: "#ffe5d9"
}

analog_board.local1: {
  input1: {
    shape: circle
    style.fill: "#8ac926"
  }
  input2: {
    shape: circle
    style.fill: "#8ac926"
  }
  input3: {
    shape: circle
    style.fill: "#8ac926"
  }
  input4: {
    shape: circle
    style.fill: "#8ac926"
  }
  input5: {
    shape: circle
    style.fill: "#8ac926"
  }
  input6: {
    shape: circle
    style.fill: "#8ac926"
  }
  input7: {
    shape: circle
    style.fill: "#8ac926"
  }
  input8: {
    shape: circle
    style.fill: "#8ac926"
  }
  shape: rectangle
}

analog_board.local2: {
  input9: {
    shape: circle
    style.fill: "#8ac926"
  }
  input10: {
    shape: circle
    style.fill: "#8ac926"
  }
  input11: {
    shape: circle
    style.fill: "#8ac926"
  }
  input12: {
    shape: circle
    style.fill: "#8ac926"
  }
  input13: {
    shape: circle
    style.fill: "#8ac926"
  }
  input14: {
    shape: circle
    style.fill: "#8ac926"
  }
  input15: {
    shape: circle
    style.fill: "#8ac926"
  }
  input16: {
    shape: circle
    style.fill: "#8ac926"
  }
  shape: rectangle
}

output: {
  xlr1: {
    shape: circle
    style.fill: "#bf0603"
  }
  xlr2: {
    shape: circle
    style.fill: "#bf0603"
  }
  xlr3: {
    shape: circle
    style.fill: "#bf0603"
  }
  xlr4: {
    shape: circle
    style.fill: "#bf0603"
  }
  xlr5: {
    shape: circle
    style.fill: "#bf0603"
  }
  xlr6: {
    shape: circle
    style.fill: "#bf0603"
  }
  xlr7: {
    shape: circle
    style.fill: "#bf0603"
  }
  xlr8: {
    shape: circle
    style.fill: "#bf0603"
  }
  shape: rectangle
}

external_board.xusb_1-8: {
  direction: down
  returns: {
    return1: {
      shape: circle
      style.fill: "#8ac926"
    }
    return2: {
      shape: circle
      style.fill: "#8ac926"
    }
    return3: {
      shape: circle
      style.fill: "#8ac926"
    }
    return4: {
      shape: circle
      style.fill: "#8ac926"
    }
    return5: {
      shape: circle
      style.fill: "#8ac926"
    }
    return6: {
      shape: circle
      style.fill: "#8ac926"
    }
    return7: {
      shape: circle
      style.fill: "#8ac926"
    }
    return8: {
      shape: circle
      style.fill: "#8ac926"
    }
  }
  sends: {
    send1: {
      shape: circle
      style.fill: "#bf0603"
    }
    send2: {
      shape: circle
      style.fill: "#bf0603"
    }
    send3: {
      shape: circle
      style.fill: "#bf0603"
    }
    send4: {
      shape: circle
      style.fill: "#bf0603"
    }
    send5: {
      shape: circle
      style.fill: "#bf0603"
    }
    send6: {
      shape: circle
      style.fill: "#bf0603"
    }
    send7: {
      shape: circle
      style.fill: "#bf0603"
    }
    send8: {
      shape: circle
      style.fill: "#bf0603"
    }
  }
  # returns -- sends
  returns.shape: cloud
  sends.shape: cloud
  shape: rectangle
}

external_board.xusb_9-16: {
  direction: down
  returns: {
    return9: {
      shape: circle
      style.fill: "#8ac926"
    }
    return10: {
      shape: circle
      style.fill: "#8ac926"
    }
    return11: {
      shape: circle
      style.fill: "#8ac926"
    }
    return12: {
      shape: circle
      style.fill: "#8ac926"
    }
    return13: {
      shape: circle
      style.fill: "#8ac926"
    }
    return14: {
      shape: circle
      style.fill: "#8ac926"
    }
    return15: {
      shape: circle
      style.fill: "#8ac926"
    }
    return16: {
      shape: circle
      style.fill: "#8ac926"
    }
  }
  sends: {
    send9: {
      shape: circle
      style.fill: "#bf0603"
    }
    send10: {
      shape: circle
      style.fill: "#bf0603"
    }
    send11: {
      shape: circle
      style.fill: "#bf0603"
    }
    send12: {
      shape: circle
      style.fill: "#bf0603"
    }
    send13: {
      shape: circle
      style.fill: "#bf0603"
    }
    send14: {
      shape: circle
      style.fill: "#bf0603"
    }
    send15: {
      shape: circle
      style.fill: "#bf0603"
    }
    send16: {
      shape: circle
      style.fill: "#bf0603"
    }
  }
  # returns -- sends
  returns.shape: cloud
  sends.shape: cloud
  shape: rectangle
}

usb key: {
  recL: {
    shape: circle
    style.fill: "#8ac926"
  }
  recR: {
    shape: circle
    style.fill: "#8ac926"
  }
  playL: {
    shape: circle
    style.fill: "#bf0603"
  }
  playR: {
    shape: circle
    style.fill: "#bf0603"
  }
  shape: rectangle
}


# actual connections
analog_board.local1.input1 -> console.slider1
analog_board.local1.input2 -> console.slider2
analog_board.local1.input3 -> console.slider3
analog_board.local1.input4 -> console.slider4
analog_board.local1.input5 -> console.slider5
analog_board.local1.input6 -> console.slider6
analog_board.local1.input7 -> console.slider7
analog_board.local1.input8 -> console.slider8

console.slider1 -> console.LR
console.slider2 -> console.LR
console.slider3 -> console.LR
console.slider4 -> console.LR
console.slider5 -> console.LR
console.slider6 -> console.LR
console.slider7 -> console.LR
console.slider8 -> console.LR

console.M -> output.xlr6
console.LR -> output.xlr7
console.LR -> output.xlr8

analog_board.local1.input1 -> external_board.xusb_1-8.sends.send1
analog_board.local1.input2 -> external_board.xusb_1-8.sends.send2
analog_board.local1.input3 -> external_board.xusb_1-8.sends.send3
analog_board.local1.input4 -> external_board.xusb_1-8.sends.send4
analog_board.local1.input5 -> external_board.xusb_1-8.sends.send5
analog_board.local1.input6 -> external_board.xusb_1-8.sends.send6
analog_board.local1.input7 -> external_board.xusb_1-8.sends.send7
analog_board.local1.input8 -> external_board.xusb_1-8.sends.send8

console.solo -> external_board.xusb_9-16.sends.send9
console.solo -> external_board.xusb_9-16.sends.send10

